// Root-level build.gradle file
buildscript {
    ext.kotlin_version = "1.9.22"
    repositories {
        // Yahan repositories reh sakti hain sirf buildscript dependencies ke liye
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-allopen:$kotlin_version"
    }
}

// Note: allprojects { repositories { ... } } block ko hata diya gaya hai
// Kyunki repositories ab settings.gradle mein manage hoti hain.

task clean(type: Delete) {
    delete rootProject.buildDir
}

